name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./1
          push: true
          platforms: linux/amd64
          tags: etsinfra/drone-bump-version:latest,etsinfra/drone-bump-version:1.2.2
